### ISSUE TITLE
Cannot cross-compile due to snprintf check

### ISSUE THREAD

**Issue by jynnantonix** [jedisct1/Blogbench#2]
I'm trying to cross-compile blogbench for arm and it's currently failing in the configure step because it cannot run test programs when cross-compiling.

Specifically, the issue appears to be this check in the configure.ac file:

```autoconf
AC_MSG_CHECKING(whether snprintf is C99 conformant)
AC_RUN_IFELSE([AC_LANG_SOURCE([[
#include <stdio.h>
#ifdef STDC_HEADERS
# include <stdlib.h>
# include <stddef.h>
#else
# if HAVE_STDLIB_H
#  include <stdlib.h>
# endif
#endif
#ifdef HAVE_UNISTD_H
# include <unistd.h>
#endif
int main(void)
{
    char buf[4];
    
    (void) fprintf(fopen("conftestval", "w"), "%d\n",
        (int) snprintf(buf, sizeof buf, "12345678"));
    return 0;
}
]])],[CONF_SNPRINTF_TYPE=`cat conftestval`
],[],[])
```

This should probably be wrapped with `AC_CACHE_CHECK` so that people can set it and there should probably be a fallback option as well.

I also wonder if this check is even still necessary.  I imagine modern compilers have C99 conformant snprintf implementations so maybe this check could even be dropped.

**Comment by jedisct1** [comment]
Yeah, we can assume that any modern operating system has a working `snprintf()` implementation :)
