### ISSUE TITLE
http://blogbench.pureftpd.org 404 not found

### ISSUE THREAD

**Issue by grahamperrin** [jedisct1/Blogbench#3]
Hi

Via the repo front page (top, right) and https://github.com/jedisct1/Blogbench/blob/ffe745ecbdde3c2f6f1d91b43504c3ec7e1036f0/README#L4

http://blogbench.pureftpd.org/ is 404, not found.

**Comment by grahamperrin** [comment]
Thanks, this remains: 

![image](https://user-images.githubusercontent.com/192271/142738441-2e39be21-53ff-41dd-8f33-f2f32934e7b5.png)

**Comment by jedisct1** [comment]
Removed, thanks!
